server:
  servlet:
#    session.timeout: 600s
    context-path: /
  port: 8070
  tomcat.uri-encoding: UTF-8

datasource:
  type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
  write:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.10.210:3306/test_analysis?useUnicode=true&amp;characterEncoding=utf-8
    username: caipiao
    password: F%46tff%^#@e
  read:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.10.210:3306/test_analysis?useUnicode=true&amp;characterEncoding=utf-8
    username: caipiao
    password: F%46tff%^#@e

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
      password: 1234qwer
  redis:
    cluster:
        nodes: 172.16.10.210:7001,172.16.10.210:7002,172.16.10.210:7003
        max-redirects: 3
    jedis:
      pool:
        max-idle: 100
        max-total: 600
        max-wait: 1000ms
    timeout: 3000ms

# MyBatis
mybatis:
    typeAliasesPackage: com.fly.caipiao.analysis.**.entity
    mapperLocations: classpath*:mapper/**/*.xml
    configuration:
      mapUnderscoreToCamelCase: true

#logger
logging:
  file: logs/analysis.log
  level:
    root: info
    com.fly.caipiao.analysis.mapper: debug

log.data.path: /data/logs/cdn_logs



