server:
  servlet:
#    session.timeout: 600s
    context-path: /
  port: 8070
  tomcat.uri-encoding: UTF-8

datasource:
  type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
  write:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.20.20.122:3306/lottery_base?useUnicode=true&amp;characterEncoding=utf-8
    username: cpuser
    password: cppass
  read:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.20.20.123:3306/lottery_base?useUnicode=true&amp;characterEncoding=utf-8
    username: cpselect
    password: cpslect!@#

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: test
      password: 1234qwer
  redis:
    cluster:
        nodes: 172.20.20.120:7000,172.20.20.119:7000,172.20.20.121:7000
        max-redirects: 3
    jedis:
      pool:
        max-idle: 100
        max-total: 600
        max-wait: 1ms

# MyBatis
mybatis:
    typeAliasesPackage: com.fly.caipiao.comment.**.entity
    mapperLocations: classpath*:mapper/**/*.xml
    configuration:
      mapUnderscoreToCamelCase: true

#logger
logging:
  file: logs/analysis.log
  level:
    root: info
    com.fly.caipiao.comment.service: debug


